NUM_INTERVALS = 24
NUM_DAY_OF_WEEK = 7
NUM_FEATURES = NUM_INTERVALS + NUM_DAY_OF_WEEK
TOP_LOC_SIZE = 24
# 1-index based
LOCATION_ID_MAX =265

HIDDEN_1_SIZE = 64
HIDDEN_2_SIZE = TOP_LOC_SIZE
HIDDEN_3_SIZE = TOP_LOC_SIZE
BATCH_SIZE = 32
NUM_ITER = 1000

KEEP_PROB_INPUT = 0.2
KEEP_PROB_HIDDEN = 0.5