NUM_INTERVALS = 24
NUM_DAY_OF_WEEK = 7
TOP_LOC_SIZE = 12
# 1-index based
LOCATION_ID_MAX =265

NUM_FEATURES = NUM_INTERVALS + NUM_DAY_OF_WEEK+LOCATION_ID_MAX*2



HIDDEN_1_SIZE = 256
HIDDEN_2_SIZE = 256
# HIDDEN_3_SIZE = TOP_LOC_SIZE
HIDDEN_3_SIZE = LOCATION_ID_MAX
BATCH_SIZE = 128
NUM_ITER = 10000

KEEP_PROB_INPUT = 1.0
KEEP_PROB_HIDDEN = 1.0